version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pgxport-test-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./test/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database inspection during development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgxport-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgxport.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local